service: apollo-lambda
provider:
  name: aws
  runtime: nodejs14.x
  timeout: 120
  iamRoleStatements:
    - Effect: 'Allow'
      Action: secretsmanager:GetSecretValue
      Resource: '*'

functions:
  graphql:
    handler: graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
